# Generated by Django 2.1.2 on 2019-02-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_price', models.IntegerField()),
                ('dish_image', models.ImageField(upload_to='Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Restaurant'),
        ),
    ]
